FROM golang:1.23-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git
COPY . .
RUN go mod download
RUN go build -mod=mod -o Gomotz ./cmd/main.go
RUN git clone https://github.com/mascarenhasmelson/tcp-tunnel-go.git /tcp-tunnel-go \
    && cd /tcp-tunnel-go \
    && go mod tidy \
    && go build -o /tcp
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/Gomotz .
COPY --from=builder /tcp ./tcp
RUN chmod +x Gomotz tcp
EXPOSE 8082
CMD ["./Gomotz"]
